/**
 * Tipos das classes de `postagem.module.css`, escritos à mão pelo mesmo motivo dos
 * outros módulos de estilo: a declaração injetada é assinatura de índice, e nome de
 * classe errado compilaria.
 */
declare const estilo: {
  readonly aviso: string;
  readonly avisoAtencao: string;
  readonly avisoCorpo: string;
  readonly avisoErro: string;
  readonly avisoTitulo: string;
  readonly botaoConferido: string;
  readonly botaoPostei: string;
  readonly cabecaAcao: string;
  readonly cabecaConferir: string;
  readonly cabecaData: string;
  readonly cabecalho: string;
  readonly cabecaLoja: string;
  readonly cabecaPedido: string;
  readonly cabecaPrazo: string;
  readonly cabecaRastreio: string;
  readonly cabecaUnidades: string;
  readonly cabecaValor: string;
  readonly campoDoRastreio: string;
  readonly cartaoDaFila: string;
  readonly cartaoDoRepasse: string;
  readonly celulaAcao: string;
  readonly conferidas: string;
  readonly contaDaFila: string;
  readonly dataDoRepasse: string;
  readonly dica: string;
  readonly divergencia: string;
  readonly divergencias: string;
  readonly entradaDoRastreio: string;
  readonly etiqueta: string;
  readonly etiquetaAlerta: string;
  readonly etiquetaAtencao: string;
  readonly etiquetaOk: string;
  readonly filaVazia: string;
  readonly filaVaziaSinal: string;
  readonly grupo: string;
  readonly grupoCabeca: string;
  readonly grupoConta: string;
  readonly grupoExplicacao: string;
  readonly grupoTitulo: string;
  readonly hoje: string;
  readonly legenda: string;
  readonly linha: string;
  readonly linhaDoGrupo: string;
  readonly loja: string;
  readonly pagina: string;
  readonly pedidoDoRepasse: string;
  readonly pedidoNumero: string;
  readonly pontoAlerta: string;
  readonly pontoAtencao: string;
  readonly pontoNeutro: string;
  readonly produto: string;
  readonly produtoSem: string;
  readonly repasse: string;
  readonly repasseAbrir: string;
  readonly repasseLoja: string;
  readonly repasses: string;
  readonly rodapeDoCartao: string;
  readonly rolagem: string;
  readonly subtitulo: string;
  readonly tabela: string;
  readonly tabelaDoRepasse: string;
  readonly textoDoCartao: string;
  readonly titulo: string;
  readonly tituloDoCartao: string;
  readonly topoDoCartao: string;
  readonly topoTextos: string;
  readonly unidades: string;
  readonly unidadesVarias: string;
  readonly valor: string;
  readonly valorAMais: string;
  readonly valorAMenos: string;
  readonly vazio: string;
};

export default estilo;
